### PR TITLE
Fix segfault in get_order_by function

### LINKED ISSUE #321: Crash when get_order_by() called with invalid relation
When `get_order_by()` is called with a valid index but an invalid relation, it causes a crash.

```
postgres=> \dx pg_repack
                                List of installed extensions
   Name    | Version | Schema |                         Description
-----------+---------+--------+--------------------------------------------------------------
 pg_repack | 1.4.7   | public | Reorganize tables in PostgreSQL databases with minimal locks
(1 row)

postgres=> select repack.get_order_by((select indexrelid from pg_catalog.pg_index order by random() limit 1), 1);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> \q
```

Backtrace
```
(gdb) bt
#0  quote_identifier (ident=ident@entry=0x0) at ruleutils.c:11469
#1  0x0000000000878c1b in quote_qualified_identifier (qualifier=0x0, ident=0x0) at ruleutils.c:11544
#2  0x000014a547ca82e0 in get_relation_name (relid=relid@entry=33926) at repack.c:415
#3  0x000014a547ca8422 in parse_indexdef (stmt=stmt@entry=0x7ffc15bdf590, index=index@entry=4158, table=33926) at repack.c:556
#4  0x000014a547ca927c in repack_get_order_by (fcinfo=<optimized out>) at repack.c:669
```

### PR DESCRIPTION
**Pull request by fabriziomello**
When pass an invalid Oid to `get_order_by` function it lead to a segmentation full in function `get_relation_name`.

Fixed if by raising an error when a table is not found.

Fixes #321

### CODE REVIEW

File: regress/sql/get_order_by.sql [hunk 1]
```diff
@@ -25,3 +25,11 @@ CREATE TABLE issue3_5 (col1 int NOT NULL, col2 text NOT NULL);
...
 SELECT repack.get_order_by('issue3_5_idx'::regclass::oid, 'issue3_5'::regclass::oid);
 \! pg_repack --dbname=contrib_regression --table=issue3_5
+
+--
+-- pg_repack issue #321
+--
+CREATE TABLE issue321 (col1 int NOT NULL, col2 text NOT NULL);
+CREATE UNIQUE INDEX issue321_idx ON issue321 (col1);
+SELECT repack.get_order_by('issue321_idx'::regclass::oid, 1);
+SELECT repack.get_order_by(1, 1);
```
Comment (dvarrazzo) [inline regress/sql/get_order_by.sql:35]: Please terminate your source with a newline, or it messes up shell tools.

**Review by dvarrazzo — CHANGES_REQUESTED** [review]
Thank you for the fix :)

File: regress/sql/get_order_by.sql (hunk 1 above)
Comment (fabriziomello) [reply regress/sql/get_order_by.sql]: Ooops... my bad... fixed!

**Comment by dvarrazzo** [comment]
I forgot to ask you to add an entry to the docs to report the issue fixed, so that's on me.

Merged, thank you very much!

**Comment by MichaelDBA** [comment]
Is this serious bug also in version 1.4.8, which was put out in October?  Will this result in a fast, official minor release soon for versions new and old affected by it?

**Comment by fabriziomello** [comment]
> I forgot to ask you to add an entry to the docs to report the issue fixed, so that's on me.
> 

Nice... next time I'll pay attention to it.

> Merged, thank you very much!

You're welcome!
